apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web
  namespace: go-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web
  template:
    metadata:
      labels:
        app: go-web
    spec:
      containers:
      - name: go-web
        image: rohanag15/go-web:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
